# Generated by Django 4.1.3 on 2022-12-03 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_options_userprofile_bio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerifyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='CAPTCHA')),
                ('email', models.EmailField(max_length=35, verbose_name='EMAIL')),
                ('send_type', models.CharField(choices=[('register', 'register'), ('forget', 'forget password')], default='register', max_length=20)),
            ],
            options={
                'verbose_name': '邮箱验证码',
                'verbose_name_plural': '邮箱验证码',
            },
        ),
    ]
