# Generated by Django 4.1.3 on 2022-12-04 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='name')),
                ('desc', models.TextField(blank=True, default='', max_length=200, verbose_name='desc')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='add_date')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='pub_date')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='name')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='add_date')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='pub_date')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tag',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=61, verbose_name='title')),
                ('desc', models.TextField(blank=True, default='', max_length=200, verbose_name='desc')),
                ('content', models.TextField(verbose_name='content')),
                ('is_hot', models.BooleanField(default=False, verbose_name='is_hot')),
                ('pv', models.IntegerField(default=0, verbose_name='pv')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='add_date')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='pub_date')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.category', verbose_name='category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='owner')),
                ('tags', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.tag', verbose_name='tag')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Post',
            },
        ),
    ]
