# Generated by Django 4.1.3 on 2022-12-04 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='category',
            name='mod_date',
            field=models.DateTimeField(auto_now=True, verbose_name='mod_date'),
        ),
        migrations.AddField(
            model_name='post',
            name='mod_date',
            field=models.DateTimeField(auto_now=True, verbose_name='mod_date'),
        ),
        migrations.AddField(
            model_name='tag',
            name='mod_date',
            field=models.DateTimeField(auto_now=True, verbose_name='mod_date'),
        ),
    ]
